title: Shao's blog
author: Shao
email: xueshaojie8@gmail.com
description: > # Snow Li's Self-learning IT blog
# social links
github_username: xueshaojie 
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

